"""Initial migration

Revision ID: 345e6f1a1764
Revises: 
Create Date: 2026-07-20 15:54:20.371163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345e6f1a1764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo_vehiculo', sa.Enum('LIVIANO', 'MOTOCICLETA', name='tipo_vehiculo', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_associations'))
    )
    op.create_index(op.f('ix_associations_created_at'), 'associations', ['created_at'], unique=False)
    op.create_index(op.f('ix_associations_nombre'), 'associations', ['nombre'], unique=True)
    op.create_index(op.f('ix_associations_tipo_vehiculo'), 'associations', ['tipo_vehiculo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código interno del fiscalizador, ej. FIS-001'),
    sa.Column('area', sa.String(length=120), nullable=True, comment='Área o gerencia a la que pertenece'),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_code'), 'users', ['code'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('codigo_qr', sa.String(length=36), nullable=False, comment='Identificador impreso en la calcomanía; permite consulta por QR'),
    sa.Column('propietario_nombre', sa.String(length=160), nullable=False),
    sa.Column('propietario_dni', sa.String(length=8), nullable=False),
    sa.Column('marca_modelo', sa.String(length=120), nullable=False),
    sa.Column('nro_motor', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('asociacion_id', sa.Integer(), nullable=True),
    sa.Column('estado_permiso', sa.Enum('VIGENTE', 'EN_TRAMITE', 'VENCIDO', name='estado_permiso', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('en_circulacion', sa.Boolean(), nullable=False),
    sa.Column('alerta_robo', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asociacion_id'], ['associations.id'], name=op.f('fk_vehicles_asociacion_id_associations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_vehicles_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index(op.f('ix_vehicles_alerta_robo'), 'vehicles', ['alerta_robo'], unique=False)
    op.create_index(op.f('ix_vehicles_asociacion_id'), 'vehicles', ['asociacion_id'], unique=False)
    op.create_index(op.f('ix_vehicles_codigo_qr'), 'vehicles', ['codigo_qr'], unique=True)
    op.create_index(op.f('ix_vehicles_created_at'), 'vehicles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicles_created_by_user_id'), 'vehicles', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vehicles_estado_permiso'), 'vehicles', ['estado_permiso'], unique=False)
    op.create_index(op.f('ix_vehicles_fecha_vencimiento'), 'vehicles', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_vehicles_placa'), 'vehicles', ['placa'], unique=True)
    op.create_index(op.f('ix_vehicles_propietario_dni'), 'vehicles', ['propietario_dni'], unique=False)
    op.create_index(op.f('ix_vehicles_propietario_nombre'), 'vehicles', ['propietario_nombre'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('tipo_inspeccion', sa.String(length=60), nullable=False, comment='Ej. RUTINARIA, OPERATIVO, DENUNCIA, RENOVACION'),
    sa.Column('estado_resultado', sa.Enum('APROBADO', 'PENDIENTE', 'RECHAZADO', name='estado_resultado', native_enum=False, length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_inspector_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_inspections_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspections_estado_resultado'), 'inspections', ['estado_resultado'], unique=False)
    op.create_index(op.f('ix_inspections_fecha'), 'inspections', ['fecha'], unique=False)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_vehicle_id'), 'inspections', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_vehicle_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_fecha'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_estado_resultado'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_vehicles_propietario_nombre'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_propietario_dni'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_placa'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fecha_vencimiento'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_estado_permiso'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_by_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_codigo_qr'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_asociacion_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_alerta_robo'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_associations_tipo_vehiculo'), table_name='associations')
    op.drop_index(op.f('ix_associations_nombre'), table_name='associations')
    op.drop_index(op.f('ix_associations_created_at'), table_name='associations')
    op.drop_table('associations')
    # ### end Alembic commands ###
